# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'
alias cls='clear'
alias ls='ls --color=auto'
alias la='ls -ah --color=auto'
alias ll='ls -lh --color=auto'
alias grep='grep --color=auto'
alias hcat='/usr/bin/hadoop/software/yarn/bin/hadoop fs -text'
alias hls='/usr/bin/hadoop/software/yarn/bin/hadoop fs -ls'
alias hrm='/usr/bin/hadoop/software/yarn/bin/hadoop fs -rm'
alias hyarn='/usr/bin/hadoop/software/yarn/bin/yarn'
rmt () { mv "$@" ~/.trash && echo "已放置回收站\n"; }
md () { mkdir -p "$@" && cd "$1";}
