# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'
alias cls='clear'
alias la='ls -ah --color=auto'
alias ls='ls -h --color=auto'
alias ll='ls -lh --color=auto'
alias grep='grep --color=auto'
alias gc='git checkout'
alias gpl='git pull'
alias gb='git branch'
alias ga='git add'
alias gp='git push'
alias gcm='git commit'
alias gl='git log'
alias gs='git status'
alias hycat='/usr/bin/hadoop/software/yarn/bin/hadoop fs -text'
alias hyls='/usr/bin/hadoop/software/yarn/bin/hadoop fs -ls'
alias hyrm='/usr/bin/hadoop/software/yarn/bin/hadoop fs -rm'
alias hyarn='/usr/bin/hadoop/software/yarn/bin/hadoop'
rmt () {	mv "$@" ~/.trash && echo "已放置回收站\n"; }
md () { mkdir -p "$@" && cd "$1";}
