# init
echo -ne "\e[5 q"

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="ys"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

plugins=(
  sudo
  tmux
  git
  wd
  history
  encode64
  jsontools
  urltools
  history-substring-search
  zsh-autosuggestions
  zsh-syntax-highlighting
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=6,bold,underline"
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

source $ZSH/oh-my-zsh.sh

# User configuration
DEFAULT_USER=`whoami`
bindkey '^R' history-incremental-search-backward
bindkey '^U' backward-kill-line

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias cls='clear'
alias ls='ls --color=auto'
alias la='ls -a --color=auto'
alias ll='ls -hl --color=auto'
alias grep='grep --color=auto'
alias hcat='/usr/bin/hadoop/software/yarn/bin/hadoop fs -text'
alias hls='/usr/bin/hadoop/software/yarn/bin/hadoop fs -ls'
alias hrm='/usr/bin/hadoop/software/yarn/bin/hadoop fs -rm'
alias hyarn='/usr/bin/hadoop/software/yarn/bin/yarn'
function rmt () { mv "$@" ~/.trash && echo "已放置回收站\n"; }
function md () { mkdir -p "$@" && cd "$1";}

export MYVIMRC=~/.vim/vimrc
export TERM=xterm-256color
export TERM_ITALICS=true
export EDITOR=vim
export GO111MODULE=on
export GOPATH=~/ToolsGoPath
export GOPROXY=https://goproxy.io
export GOBIN=$GOPATH/bin
export GOROOT=/usr/local/go
export GOTMPDIR=~/ToolsGoPath/tmp
export PATH=$PATH:$GOPATH/bin:~/Software
