# init
echo -ne "\e[5 q"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
#ZSH_THEME="robbyrussell"
ZSH_THEME="ys"

# zsh features switch
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="false"
DISABLE_AUTO_UPDATE="false"
export UPDATE_ZSH_DAYS=13
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="false"
HIST_STAMPS="yyyy-mm-dd"
ZSH_CUSTOM=$ZSH/custom

plugins=(
  sudo
  tmux
  git
  wd
  history
  encode64
  jsontools
  urltools
  fzf
  history-substring-search
  zsh-autosuggestions
  zsh-syntax-highlighting
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=6,bold,underline"
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

source $ZSH/oh-my-zsh.sh

# User configuration
#bindkey '^R' history-incremental-search-backward
#bindkey '^U' backward-kill-line

# User locale config
if [ -f ${HOME}/.config/locale.conf ]; then
    . ${HOME}/.config/locale.conf
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# For a full list of active aliases, run `alias`.
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"
if [ -f ${HOME}/.config/alias.conf ]; then
    . ${HOME}/.config/alias.conf
fi

# env config
export DEFAULT_USER=$USER
export MANPATH="/usr/local/man:$MANPATH"
if [ -f ${HOME}/.config/env.conf ]; then
    . ${HOME}/.config/env.conf
fi
