###
# @Author      : caodaqian
# @since       : 2020-09-09 10:41:33
# @LastEditors : caodaqian
# @lastTime    : 2020-09-09 11:00:40
# @Description : .zshrc
###

# init
echo -ne "\e[5 q"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
#ZSH_THEME="robbyrussell"
ZSH_THEME="ys"

# zsh features switch
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="false"
DISABLE_AUTO_UPDATE="false"
export UPDATE_ZSH_DAYS=13
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="false"
HIST_STAMPS="yyyy-mm-dd"
ZSH_CUSTOM=$ZSH/custom

plugins=(
    sudo
    tmux
    git
    wd
    history
    encode64
    jsontools
    urltools
    fzf
    history-substring-search
    zsh-autosuggestions
    zsh-syntax-highlighting
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=6,bold,underline"
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

source $ZSH/oh-my-zsh.sh

# User configuration
#bindkey '^R' history-incremental-search-backward
#bindkey '^U' backward-kill-line

# default env, alias and locale
[[ -f ${HOME}/.bash_profile ]] && source ${HOME}/.bash_profile

# user alias
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"

# user env
export DEFAULT_USER=$USER
export MANPATH="/usr/local/man:$MANPATH"
export SSH_KEY_PATH="~/.ssh/rsa_id"
