###
# @Author      : caodaqian
# @since       : 2020-09-09 10:41:53
# @LastEditors : caodaqian
# @lastTime    : 2020-09-09 10:42:09
# @Description : .bashrc
###

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

[[ -f ${HOME}/.bash_profile ]] && source ${HOME}/.bash_profile

## fzf config
[ -f ${HOME}/.fzf.bash ] && source ${HOME}/.fzf.bash
